- public  
- protected
- default
- private  
- static 변수     정적변수
- static 메서드  정적메서드
- final 변수  변하지 않는 상수
- final 메서드   
- final 클래스   
- abstract 클래스
- abstract 메서드
- interface
- abstract class
- extends    
- implements  
- this
- super       부모메서드 받아오기
- 오버로딩
- 오버라이딩
- try        예외처리문구
- catch    
- finally    무조건 실행